### ISSUE TITLE
The Connection Manager is a libp2p module

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-connection-manager#1]
Hey @pgte mind moving this to libp2p? It should be designed for libp2p and not just IPFS.

**Comment by pgte** [comment]
@diasdavid The way I'm thinking of implementing this, it needs bitswap stats to be able to assign a value on each peer..
https://github.com/ipfs/dynamic-data-and-capabilities/issues/3#issuecomment-361919002

**Comment by diasdavid** [comment]
That means that libp2p-connection-manager has to have a way to receive inputs from the application that uses it.

**Comment by diasdavid** [comment]
**a)** looks like the right one to me :)

**Comment by pgte** [comment]
Moved and renamed. Thanks!
