### ISSUE TITLE
Async Refactor

### ISSUE THREAD

**Issue by kumavis** [libp2p/js-libp2p-connection-manager#21]
@vasco-santos  I was looking at taking on `libp2p-connection-manager` but it seems all synchronous, except for the consumption and emission of events

what were you planning for the async refactor?

**Comment by vasco-santos** [comment]
We made a list of all the modules in the [Awesome Endeavour: Async Iterators](https://github.com/ipfs/js-ipfs/issues/1670). I looked into the codebase for `connection-manager` and it looks to me that, in fact, we do not need to make any change here! This way, this module should be a blocker to any other module.

**Comment by kumavis** [comment]
@vasco-santos so should we mark `libp2p-connection-manager` as done in the awesome endeavour? its currently `P0`

**Comment by vasco-santos** [comment]
My main doubt with that is our intention to improve the connection manager API (which may include async stuff). 

However, as we want to drastically improve the connection manager in the near future, I think that we can tackle that by then and consider this module not applicable in the `Awesome Endeavour: Async Iterators`, as the future changes will not be a refactor. Do you agree @jacobheun ?

**Comment by vasco-santos** [comment]
Cool, just updated the table!
